org: vitali87
app: my-first-app
# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
plugins:
  -serverless-offline
